name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Change this to your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker-compose build
          docker tag your-repo-name:latest <account-id>.dkr.ecr.<region>.amazonaws.com/your-repo-name:latest

      - name: Push Docker Image to ECR
        run: |
          docker push <account-id>.dkr.ecr.<region>.amazonaws.com/your-repo-name:latest
